import type { Metadata } from "next";
import "./globals.css";
import { georama, robotoMono } from "./font";

export const metadata: Metadata = {
  title: "Kris's Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: "/macbook.png"
  }
};

import { ThemeProvider } from "./components/ThemeProvider";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={`${georama.variable} ${robotoMono.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}

